### ISSUE TITLE
Shooter - PID Values and Tuning

### ISSUE THREAD

**Issue by AsherN-chuck** [chuck2147/offseason-2021#2]
For the shooter we need to be able to shoot from different spots on the field. 
These shots include:

- Triangle
  - NOTE:  We cannot do this one at any wheel speed.  The top wheel will have to move back to do this.
- Behind the initiation line
- Protected trench - closer to goal
- 3/4 of the field - in the protected trench and behind the wheel.
 
We also need to tune the PID so that it is as accurate as it can possibly be.

**Comment by calebeby** [comment]
@AsherN-chuck can we make separate issues for:

- Tune the shooting numbers for the 3-4 different positions
- Set up limelight tracking for aligning the robot to the goal
- Set up limelight tracking for determining the wheel speeds based on the estimated distance to the goal

**Comment by AsherN-chuck** [comment]
Ok I split the Limelight and the PID/Tuning into two separate issues. If you want me to change anything let me know.
