### ISSUE TITLE
Shooter - LimeLight Tracking 

### ISSUE THREAD

**Issue by AsherN-chuck** [chuck2147/offseason-2021#6]
We need to set up Limelight for the shooter so we can determine the correct velocity for each one of the shooter wheels at specific distances. Limelight also needs to be able to see where the robot is on the field and which way it is rotated and align it with the goal.

**Comment by BrockPopek** [comment]
First thing to be done with this item is to get measurements of the top and bottom wheel speeds at various distances from the goal.  Then we can put that into a table for lookup and/or formulation of wheel speeds between distance points.

**Comment by BrockPopek** [comment]
Item was not finished by PNW Block Party competition.  Closing the item out.
